controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

callback:
    path: /callback
    controller: App\Controller\CallbackController::index
