<?php

namespace ContainerLTQ1exf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V6sch5AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v6sch5A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v6sch5A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artist' => ['privates', '.errored..service_locator.v6sch5A.App\\Entity\\Artist', NULL, 'Cannot autowire service ".service_locator.v6sch5A": it needs an instance of "App\\Entity\\Artist" but this type has been excluded in "config/services.yaml".'],
        ], [
            'artist' => 'App\\Entity\\Artist',
        ]);
    }
}
