<?php

namespace ContainerLTQ1exf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z2a8Gv9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z2a8Gv9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z2a8Gv9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'album' => ['privates', '.errored..service_locator.z2a8Gv9.App\\Entity\\Album', NULL, 'Cannot autowire service ".service_locator.z2a8Gv9": it needs an instance of "App\\Entity\\Album" but this type has been excluded in "config/services.yaml".'],
            'albumRepository' => ['privates', 'App\\Repository\\AlbumRepository', 'getAlbumRepositoryService', true],
        ], [
            'album' => 'App\\Entity\\Album',
            'albumRepository' => 'App\\Repository\\AlbumRepository',
        ]);
    }
}
