<?php

namespace ContainerLTQ1exf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MV3wr36Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MV3wr36' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MV3wr36'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'track' => ['privates', '.errored..service_locator.MV3wr36.App\\Entity\\Track', NULL, 'Cannot autowire service ".service_locator.MV3wr36": it needs an instance of "App\\Entity\\Track" but this type has been excluded in "config/services.yaml".'],
        ], [
            'track' => 'App\\Entity\\Track',
        ]);
    }
}
