<?php

namespace ContainerLTQ1exf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RaQdCkhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.raQdCkh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.raQdCkh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'track' => ['privates', '.errored..service_locator.raQdCkh.App\\Entity\\Track', NULL, 'Cannot autowire service ".service_locator.raQdCkh": it needs an instance of "App\\Entity\\Track" but this type has been excluded in "config/services.yaml".'],
            'trackRepository' => ['privates', 'App\\Repository\\TrackRepository', 'getTrackRepositoryService', true],
        ], [
            'track' => 'App\\Entity\\Track',
            'trackRepository' => 'App\\Repository\\TrackRepository',
        ]);
    }
}
