<?php

namespace ContainerLTQ1exf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LSEC9EkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LSEC9Ek' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LSEC9Ek'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AlbumController::delete' => ['privates', '.service_locator.z2a8Gv9', 'get_ServiceLocator_Z2a8Gv9Service', true],
            'App\\Controller\\AlbumController::edit' => ['privates', '.service_locator.z2a8Gv9', 'get_ServiceLocator_Z2a8Gv9Service', true],
            'App\\Controller\\AlbumController::index' => ['privates', '.service_locator.EgUKVN3', 'get_ServiceLocator_EgUKVN3Service', true],
            'App\\Controller\\AlbumController::new' => ['privates', '.service_locator.EgUKVN3', 'get_ServiceLocator_EgUKVN3Service', true],
            'App\\Controller\\AlbumController::show' => ['privates', '.service_locator.KOhdJhL', 'get_ServiceLocator_KOhdJhLService', true],
            'App\\Controller\\ArtistController::delete' => ['privates', '.service_locator.BBU45Qh', 'get_ServiceLocator_BBU45QhService', true],
            'App\\Controller\\ArtistController::edit' => ['privates', '.service_locator.BBU45Qh', 'get_ServiceLocator_BBU45QhService', true],
            'App\\Controller\\ArtistController::index' => ['privates', '.service_locator.gjefEio', 'get_ServiceLocator_GjefEioService', true],
            'App\\Controller\\ArtistController::new' => ['privates', '.service_locator.gjefEio', 'get_ServiceLocator_GjefEioService', true],
            'App\\Controller\\ArtistController::show' => ['privates', '.service_locator.v6sch5A', 'get_ServiceLocator_V6sch5AService', true],
            'App\\Controller\\GenreController::delete' => ['privates', '.service_locator.l1zIsd0', 'get_ServiceLocator_L1zIsd0Service', true],
            'App\\Controller\\GenreController::edit' => ['privates', '.service_locator.l1zIsd0', 'get_ServiceLocator_L1zIsd0Service', true],
            'App\\Controller\\GenreController::index' => ['privates', '.service_locator.LHZBpiL', 'get_ServiceLocator_LHZBpiLService', true],
            'App\\Controller\\GenreController::new' => ['privates', '.service_locator.LHZBpiL', 'get_ServiceLocator_LHZBpiLService', true],
            'App\\Controller\\GenreController::show' => ['privates', '.service_locator.tEjJDpv', 'get_ServiceLocator_TEjJDpvService', true],
            'App\\Controller\\TrackController::delete' => ['privates', '.service_locator.raQdCkh', 'get_ServiceLocator_RaQdCkhService', true],
            'App\\Controller\\TrackController::edit' => ['privates', '.service_locator.raQdCkh', 'get_ServiceLocator_RaQdCkhService', true],
            'App\\Controller\\TrackController::index' => ['privates', '.service_locator.nerdE7U', 'get_ServiceLocator_NerdE7UService', true],
            'App\\Controller\\TrackController::new' => ['privates', '.service_locator.nerdE7U', 'get_ServiceLocator_NerdE7UService', true],
            'App\\Controller\\TrackController::show' => ['privates', '.service_locator.MV3wr36', 'get_ServiceLocator_MV3wr36Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AlbumController:delete' => ['privates', '.service_locator.z2a8Gv9', 'get_ServiceLocator_Z2a8Gv9Service', true],
            'App\\Controller\\AlbumController:edit' => ['privates', '.service_locator.z2a8Gv9', 'get_ServiceLocator_Z2a8Gv9Service', true],
            'App\\Controller\\AlbumController:index' => ['privates', '.service_locator.EgUKVN3', 'get_ServiceLocator_EgUKVN3Service', true],
            'App\\Controller\\AlbumController:new' => ['privates', '.service_locator.EgUKVN3', 'get_ServiceLocator_EgUKVN3Service', true],
            'App\\Controller\\AlbumController:show' => ['privates', '.service_locator.KOhdJhL', 'get_ServiceLocator_KOhdJhLService', true],
            'App\\Controller\\ArtistController:delete' => ['privates', '.service_locator.BBU45Qh', 'get_ServiceLocator_BBU45QhService', true],
            'App\\Controller\\ArtistController:edit' => ['privates', '.service_locator.BBU45Qh', 'get_ServiceLocator_BBU45QhService', true],
            'App\\Controller\\ArtistController:index' => ['privates', '.service_locator.gjefEio', 'get_ServiceLocator_GjefEioService', true],
            'App\\Controller\\ArtistController:new' => ['privates', '.service_locator.gjefEio', 'get_ServiceLocator_GjefEioService', true],
            'App\\Controller\\ArtistController:show' => ['privates', '.service_locator.v6sch5A', 'get_ServiceLocator_V6sch5AService', true],
            'App\\Controller\\GenreController:delete' => ['privates', '.service_locator.l1zIsd0', 'get_ServiceLocator_L1zIsd0Service', true],
            'App\\Controller\\GenreController:edit' => ['privates', '.service_locator.l1zIsd0', 'get_ServiceLocator_L1zIsd0Service', true],
            'App\\Controller\\GenreController:index' => ['privates', '.service_locator.LHZBpiL', 'get_ServiceLocator_LHZBpiLService', true],
            'App\\Controller\\GenreController:new' => ['privates', '.service_locator.LHZBpiL', 'get_ServiceLocator_LHZBpiLService', true],
            'App\\Controller\\GenreController:show' => ['privates', '.service_locator.tEjJDpv', 'get_ServiceLocator_TEjJDpvService', true],
            'App\\Controller\\TrackController:delete' => ['privates', '.service_locator.raQdCkh', 'get_ServiceLocator_RaQdCkhService', true],
            'App\\Controller\\TrackController:edit' => ['privates', '.service_locator.raQdCkh', 'get_ServiceLocator_RaQdCkhService', true],
            'App\\Controller\\TrackController:index' => ['privates', '.service_locator.nerdE7U', 'get_ServiceLocator_NerdE7UService', true],
            'App\\Controller\\TrackController:new' => ['privates', '.service_locator.nerdE7U', 'get_ServiceLocator_NerdE7UService', true],
            'App\\Controller\\TrackController:show' => ['privates', '.service_locator.MV3wr36', 'get_ServiceLocator_MV3wr36Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AlbumController::delete' => '?',
            'App\\Controller\\AlbumController::edit' => '?',
            'App\\Controller\\AlbumController::index' => '?',
            'App\\Controller\\AlbumController::new' => '?',
            'App\\Controller\\AlbumController::show' => '?',
            'App\\Controller\\ArtistController::delete' => '?',
            'App\\Controller\\ArtistController::edit' => '?',
            'App\\Controller\\ArtistController::index' => '?',
            'App\\Controller\\ArtistController::new' => '?',
            'App\\Controller\\ArtistController::show' => '?',
            'App\\Controller\\GenreController::delete' => '?',
            'App\\Controller\\GenreController::edit' => '?',
            'App\\Controller\\GenreController::index' => '?',
            'App\\Controller\\GenreController::new' => '?',
            'App\\Controller\\GenreController::show' => '?',
            'App\\Controller\\TrackController::delete' => '?',
            'App\\Controller\\TrackController::edit' => '?',
            'App\\Controller\\TrackController::index' => '?',
            'App\\Controller\\TrackController::new' => '?',
            'App\\Controller\\TrackController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AlbumController:delete' => '?',
            'App\\Controller\\AlbumController:edit' => '?',
            'App\\Controller\\AlbumController:index' => '?',
            'App\\Controller\\AlbumController:new' => '?',
            'App\\Controller\\AlbumController:show' => '?',
            'App\\Controller\\ArtistController:delete' => '?',
            'App\\Controller\\ArtistController:edit' => '?',
            'App\\Controller\\ArtistController:index' => '?',
            'App\\Controller\\ArtistController:new' => '?',
            'App\\Controller\\ArtistController:show' => '?',
            'App\\Controller\\GenreController:delete' => '?',
            'App\\Controller\\GenreController:edit' => '?',
            'App\\Controller\\GenreController:index' => '?',
            'App\\Controller\\GenreController:new' => '?',
            'App\\Controller\\GenreController:show' => '?',
            'App\\Controller\\TrackController:delete' => '?',
            'App\\Controller\\TrackController:edit' => '?',
            'App\\Controller\\TrackController:index' => '?',
            'App\\Controller\\TrackController:new' => '?',
            'App\\Controller\\TrackController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
