<?php

namespace ContainerLTQ1exf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BBU45Qh.App\Entity\Artist' shared service.
     *
     * @return \App\Entity\Artist
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BBU45Qh": it needs an instance of "App\\Entity\\Artist" but this type has been excluded in "config/services.yaml".');
    }
}
