<?php

namespace ContainerLTQ1exf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbum2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.z2a8Gv9.App\Entity\Album' shared service.
     *
     * @return \App\Entity\Album
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.z2a8Gv9": it needs an instance of "App\\Entity\\Album" but this type has been excluded in "config/services.yaml".');
    }
}
