<?php

namespace ContainerLTQ1exf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrack2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.raQdCkh.App\Entity\Track' shared service.
     *
     * @return \App\Entity\Track
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.raQdCkh": it needs an instance of "App\\Entity\\Track" but this type has been excluded in "config/services.yaml".');
    }
}
