<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLTQ1exf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLTQ1exf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLTQ1exf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLTQ1exf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLTQ1exf\App_KernelDevDebugContainer([
    'container.build_hash' => 'LTQ1exf',
    'container.build_id' => '116ea043',
    'container.build_time' => 1680094792,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLTQ1exf');
