<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_album_index' => [[], ['_controller' => 'App\\Controller\\AlbumController::index'], [], [['text', '/album/']], [], [], []],
    'app_album_new' => [[], ['_controller' => 'App\\Controller\\AlbumController::new'], [], [['text', '/album/new']], [], [], []],
    'app_album_show' => [['id'], ['_controller' => 'App\\Controller\\AlbumController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_album_edit' => [['id'], ['_controller' => 'App\\Controller\\AlbumController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_album_delete' => [['id'], ['_controller' => 'App\\Controller\\AlbumController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_artist_index' => [[], ['_controller' => 'App\\Controller\\ArtistController::index'], [], [['text', '/artist/']], [], [], []],
    'app_artist_new' => [[], ['_controller' => 'App\\Controller\\ArtistController::new'], [], [['text', '/artist/new']], [], [], []],
    'app_artist_show' => [['id'], ['_controller' => 'App\\Controller\\ArtistController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/artist']], [], [], []],
    'app_artist_edit' => [['id'], ['_controller' => 'App\\Controller\\ArtistController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/artist']], [], [], []],
    'app_artist_delete' => [['id'], ['_controller' => 'App\\Controller\\ArtistController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/artist']], [], [], []],
    'app_genre_index' => [[], ['_controller' => 'App\\Controller\\GenreController::index'], [], [['text', '/genre/']], [], [], []],
    'app_genre_new' => [[], ['_controller' => 'App\\Controller\\GenreController::new'], [], [['text', '/genre/new']], [], [], []],
    'app_genre_show' => [['id'], ['_controller' => 'App\\Controller\\GenreController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/genre']], [], [], []],
    'app_genre_edit' => [['id'], ['_controller' => 'App\\Controller\\GenreController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/genre']], [], [], []],
    'app_genre_delete' => [['id'], ['_controller' => 'App\\Controller\\GenreController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/genre']], [], [], []],
    'app_track_index' => [[], ['_controller' => 'App\\Controller\\TrackController::index'], [], [['text', '/track/']], [], [], []],
    'app_track_new' => [[], ['_controller' => 'App\\Controller\\TrackController::new'], [], [['text', '/track/new']], [], [], []],
    'app_track_show' => [['id'], ['_controller' => 'App\\Controller\\TrackController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/track']], [], [], []],
    'app_track_edit' => [['id'], ['_controller' => 'App\\Controller\\TrackController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/track']], [], [], []],
    'app_track_delete' => [['id'], ['_controller' => 'App\\Controller\\TrackController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/track']], [], [], []],
];
